### ISSUE TITLE
0xnevi - [H-01] Restrictive equality check in `PositionManager.moveLiquidity()` can potentially unfairly not allow liquidity holders move liquidity

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-ajna-judging#10]
0xnevi

high

# [H-01] Restrictive equality check in `PositionManager.moveLiquidity()` can potentially unfairly not allow liquidity holders move liquidity

## Summary
Restrictive equality check in `PositionManager.moveLiquidity()` can potentially unfairly not allow liquidity holders to move liquidity

## Vulnerability Detail
```solidity
if (vars.fromLP != vars.lpbAmountFrom) revert RemovePositionFailed(); // bucket has collateral and quote therefore LP is not redeemable for full quote token amount
```

Since amount of liquidity token to move calculated is dependent on amount of deposit, claimable collateral and total lpb tokens in pool, it is very unlikely that the initial LP amount moved from position memorialized to NFT recorded at time of deposit will be always equal to lp token to move at time of moving after swap based on current bucket exchange rate in pool. This can result in 2 scenarios:

1. If fromlp determined to move via `moveQuoteToken()` is lesser than the original amount of lpToken tied to NFT, user cannot move liquidity to another bucket

2. If fromlp determined to move via `moveQuoteToken()` is more than the original amount of lpToken tied to NFT, user will be unfairly not allowed to move liquidity.

The above check mentioned could be too restrictive since deposits and claimable collateral along with amount of lp tokens in pool can change anytime and as such bucket exchange rates will not remain constant. Or it could simply be due to the fact that bucket still has collateral and quote token.

## Impact
Refer to Vulnerability Detail section

## Code Snippet
https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/PositionManager.sol#L362

## Tool used

Manual Review

## Recommendation
The above check is not required since collateral, deposits and lpb will be updated accordingly via `moveQuoteToken()`.

However, since we cannot guarantee that the lp tokens to move out will always be equal to original lp balance memorialized to NFT, perhaps a slippage parameter could be introduced since a swap is involved when moving liquidity, that allows revert if lp amount to move from old bucket to new bucket does not meet minimum amount.

**Comment by nevillehuang** [comment]
Escalate for 10 USDC
According to sponsor this is technically correct and functionality is not well documented anywhere except a pretty ambiguous comment, so I think it is fair for me to treat it as a vulnerability instead of a feature.

https://discord.com/channels/812037309376495636/1115293970315096235/1125488151960485948

**Comment by 0xffff11** [comment]
I would like to know @grandizzy opinion on this one. I don't know if I see it as a medium. I don't see any funds being affected here, but let me know if I am mistaken

Sponsors reasoning for the restrictive check:
'''
There is a possibility that there is collateral in the bucket they are moving from, if so the move liquidity caller wouldn't move their entire position. We didn't want this experience so this check causes that scenario to revert.
'''

**Comment by nevillehuang** [comment]
> I would like to know @grandizzy opinion on this one. I don't know if I see it as a medium. I don't see any funds being affected here, but let me know if I am mistaken
> 
> Sponsors reasoning for the restrictive check: ''' There is a possibility that there is collateral in the bucket they are moving from, if so the move liquidity caller wouldn't move their entire position. We didn't want this experience so this check causes that scenario to revert. '''

Not allowing moving of liquidity to other buckets could potentially result in losses such as when bucket is close to bankruptcy or when other buckets have a better exchange rate.

**Comment by ith-harvey** [comment]
I don't believe this issue should result in a reward. The code as it stands streamlines the moveLiquidity method by reverting if a user calls moveLiquidity when the bucket they are moving from has collateral / quote. This added measure makes the code easier to reason about.

The actor who calls this method and subsequently receives a revert is welcome to redeem their position, retaining all of their value.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a valid low based on the Sponsor comment

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [nevillehuang](https://github.com/sherlock-audit/2023-04-ajna-judging/issues/10/#issuecomment-1619023814): rejected
