### ISSUE TITLE
PRAISE - using _mint() in PositionManager.sol can mint NFTs to a contract that cannot handle NFTs.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-ajna-judging#11]
PRAISE

medium

# using _mint() in PositionManager.sol can mint NFTs to a contract that cannot handle NFTs.

## Summary
if the `recipient_` is a contract using _mint() instead of _safeMint() can mint NFTS to a contract that cannot handle NFTS

## Vulnerability Detail
PositionManager.mint() uses _mint() to mint NFTS to the `recipient_`
```solidity

        _mint(recipient_, tokenId_);//@audit-info this can mint NFT to a contract that cannot handle nfts.

```
So since the `recipient_` can be both an EOA and a contract / proxy, if its a contract that cannot handle NFTS using _safeMInt() instead of _mint() would have been able to stop it.

## Impact
PositionManager.mint()  might mint NFTs to a contract that cannot handle NFTs.

## Code Snippet
https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/PositionManager.sol#L280
## Tool used

Manual Review

## Recommendation
 Use _safeMint() instead of _mint() because it checks and ensures that NFTs are only minted to contracts that can handle NFTS.
`      if (!_checkOnERC721Received(address(0), to, tokenId, data)) {
            revert ERC721InvalidReceiver(to);
        }`
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/05ef6924ac7e5db711c9bd588479c559bd383aba/contracts/token/ERC721/ERC721.sol#L255

**Comment by Love4codes** [comment]
Escalate for 10 USDC

Same as the reason I gave for my transferFrom issue. _mint() might mint to contracts that can't handle NFTs

**Comment by securitygrid** [comment]
Comment from a watson:
It is recommended that you save 10 USDC. This is the caller's own fault. Not a valid issue.
