### ISSUE TITLE
PRAISE - use safeTransferFrom() instead of transferFrom() in _transferNFT,  NFTs could be locked if the receiver is a contract and doesn't implement onERC721 received

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-ajna-judging#12]
PRAISE

high

# use safeTransferFrom() instead of transferFrom() in _transferNFT,  NFTs could be locked if the receiver is a contract and doesn't implement onERC721 received

## Summary
safeTransferFrom() should be used instead of transferFrom()
## Vulnerability Detail
```solidity
  IERC721Token(_getArgAddress(COLLATERAL_ADDRESS)).transferFrom(from_, to_, tokenId_);
```
using  transferFrom() for NFTs can have the NFTs locked if the receiver is a contract and doesn't implement onERC721 received.

## Impact
NFTs will be locked if the receiver is a contract that doesn't implement onERC721 received

## Code Snippet
https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/ERC721Pool.sol#L624

https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/RewardsManager.sol#L813
## Tool used

Manual Review

## Recommendation
use safeTransferFrom() instead of transferFrom() in _transferNFT

**Comment by Love4codes** [comment]
Escalate for 10 USDC

TransferFrom isn't safe

**Comment by securitygrid** [comment]
Comment from a watson:
It is recommended that you save 10 USDC. This is the caller's own fault. Not a valid issue. safeTransferFrom will bring reenterancy attack.
