### ISSUE TITLE
MohammedRizwan - Minting NFTs to contract address will fail(Missing issue in documentation too)

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-ajna-judging#18]
MohammedRizwan

medium

# Minting NFTs to contract address will fail(Missing issue in documentation too)

First of all before going deep in below report, I had a detail discussion with sponsors in discord private chat and the issue is confirmed with some agreed solution which is mentioned in recommendations and agreed for a fix by sponsors.

## Summary
Minting NFTs to contract address will fail. Use safeMint instead of mint for Minting NFTs to contract address.

## Impact

In PositionManager.mint(), If the recipient_ is the contract address which unable to receive ERC721 token or it does not implement the onERC721Received method, the NFT will be permanently locked or frozen in the contract which will happen in the current implementation mint( ) functions as shown below,

```solidity
File: src/PositionManager.sol

267    function mint(
268        address pool_,
269        address recipient_,
270        bytes32 poolSubsetHash_
271    ) external override nonReentrant returns (uint256 tokenId_) {
272        // revert if the address is not a valid Ajna pool
273        if (!_isAjnaPool(pool_, poolSubsetHash_)) revert NotAjnaPool();
274
275        tokenId_ = _nextId++;
276
277        // record which pool the tokenId was minted in
278        positionTokens[tokenId_].pool = pool_;
279
280        _mint(recipient_, tokenId_);
281
282        emit Mint(recipient_, pool_, tokenId_);
283    }
```
_mint( ) function won’t check if the recipient is able to receive the NFT. If an incorrect address is passed, it will result in a silent failure and loss of asset.

As per ERC721.sol by Openzeppelin, Use of _mint() is discouraged, use _safeMint() whenever possible.
[Link to openzeppelin reference](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/cd48b3eab380254b08d7893a5a7bf568a33c5259/contracts/token/ERC721/ERC721.sol#L263)

As per ERC721.sol by Openzeppelin, If `recipient` is a smart contract, it must implement {IERC721Receiver-onERC721Received}
[Link to openzeppelin reference](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/cd48b3eab380254b08d7893a5a7bf568a33c5259/contracts/token/ERC721/ERC721.sol#L241-L247)

**Discussion with Sponsors(@dizzy):**
I had a detail discussion on safeMint() along with safeTransferFrom()(already reported in another issue) usage instead of _mint() in mint() function at L-280. I explained the impact of not using _mint(() function which with current implementation will not be able to transfer the NFTs to contract address and lock the user NFTs.  It was also discussed the scenario after account abstraction will fully rollout where smart contracts will handle as account. While discussion, it was said the contracts will be used by some already deployed proxy contract. This proxy contract holds tokens. Inshort the contracts will used via. proxy contracts. Now the issue is the proxy contract does not implement the onERC721Received support which for sure wont be able to receive the NFTs and if the NFTs sent to contract address with NO onERC721Received support will lock or freeze the NFTs permanently. It also does not seems to be possible for redeployment of proxy contract to mitigate the issue. After all Pros and Cons, It was decided to go with current implementation only but these critical issues are NOT documented anywhere. These critical issue are not aware to users and integrators.

Discussion link for reference- https://discord.com/channels/@me/1119210314811056128/1119268553221214359

Please be noted Ajna 1st Sherlock contest had used safeMint() but later after discussion with integrators on purposely use of transferFrom() to allow integrators use their existing contracts / proxies., Now it has used mint().

Old contract link with safeMint() implementation-
https://github.com/sherlock-audit/2023-01-ajna/blob/69732cef929414a95be9a722a2f1aafec7c2ab0f/contracts/src/PositionManager.sol#L194

## Code Snippet
https://github.com/ajna-finance/ajna-core/blob/e3632f6d0b196fb1bf1e59c05fb85daf357f2386/src/PositionManager.sol#L280

## Tool used
Manual Review

## Recommendation
1) Use safeMint instead of mint to check received address support for ERC721 implementation with reentrancy protection. But as per the detail discussion on this topic, this does not seems to be possible presently.
2) Make a clear documents stating above issues pertaining to MINTING of NFTs to contract addresses, also alert users the impact of MINTING the NFT to contract address at Front-end user interface(UI).
3) As discussed and agreed, Kindly mention these critical issues clearly in documentation for USERS as well as for INTEGRATORS to make sure their contracts support the NFT and they are not end up locked NFTs in their contracts.

**Comment by grandizzy** [comment]
to clarify: usage of plain transfer is a deliberate choice but since this issue was raised in several audits the reasons of doing such should be better document / explicitly stated in repo README / limitations

**Comment by mohammedrizwann123** [comment]
Escalate for 10USDC

I have explained about this escalation in #17 as both issues are confirmed and discussed with sponsor(@grandizzy).

Thank you.

**Comment by 0xffff11** [comment]
I am sorry, not using _safeMint over _mint, it is not a vulnerability. Contracts interacting with Ajna should make their due diligence and build according to the current implementation. Ajna should add it as a remainder, but this is not a vulnerability. Invalid

**Comment by dmitriia** [comment]
Agree, that's a clear design choice. Bear in mind that safe methods do introduce reentrancy, so basically every project has a choice either to handle it or to use non-safe versions, with the answer heavily depending on the particular logic.

**Comment by mohammedrizwann123** [comment]
@dmitriia @0xffff11 

Withdue respect, @dmitriia Agreed, The reports describe the issues why the previous V1 contracts(Ajna Sherlock first contest) has adopted transferFrom() and mint() instead of safeTransferFrom() and safeMint(). This is because due to integrator contracts issue.

As per my discussion with @grandizzy, the reports focuses on recommendation(See point 2 and 3),

> Make a clear documents stating above issues pertaining to MINTING of NFTs to contract addresses, also alert users the impact of MINTING the NFT to contract address at Front-end user interface(UI).

> As discussed and agreed, Kindly mention these critical issues clearly in documentation for USERS as well as for INTEGRATORS to make sure their contracts support the NFT and they are not end up locked NFTs in their contracts.

**No where it is enforcing to use the safeTransferFrom and safeMint() functions.** I do understand and respect protocols design which can be altered like in this case due to integrator issue.

As per my detail discussion with @grandizzy, the intension of both (#17 and #18) is first to highlight the following points,

1) What exactly the issue is in contracts and how it differ from V1 contracts.
2) Why sponsors has adopted transferFrom() and mint() as compared to V1 contracts.
3) What exactly the sponsor is looking to mitigate the issue.

As per my discussion with @grandizzy, the (#17 and #18) was also asked by Code4rena team. So that where the need of making and submitting these reports came from. I am sure, these issues will further be raised in future with respect to your integrators and users. 

I agree this must be documented but these findings should make to final report. Please dont just consider it informational issue, If it was informational then i would have just texted to @grandizzy like i highlighted the Signature malleability issue due to openzeppelin version(ECDSA has that issue but recover function does not applicable for this vulnerability).

The issue here, it is seen from low/informational point of view.

@grandizzy also agreed with above findings being in report and explanation. 

Thank you.

**Comment by dmitriia** [comment]
I do agree that is a valid low.

There is actually safeMint example in Sherlock docs:

https://docs.sherlock.xyz/audits/judging/judging#list-of-issue-categories-that-are-not-considered-valid

> ERC721 unsafe mint: In case of a protocol implementing minting/claiming of ERC721, users being unable to do so due to incorrect implementation is not a valid issue. 
Example: https://github.com/sherlock-audit/2023-03-teller-judging/issues/8

**Comment by mohammedrizwann123** [comment]
@dmitriia agreed on #18, Thank you for sharing the reference, would take care in future reports. 

For #17 per my above explanation. #17 should atleast be acknowledged. The Readme.md does not mention transferFrom() issue as known issue or design choice or integrator issue. There is definately loss of asset in case the recepient is contract address with no ERC721Received implemenation/support per openzeppelin. In known issues, V1 contract changes should have been mentioned in Readme.md for information and exclusions from submissions. This is something missed from Ajna team as V1 contracts were also audited by Sherlock.

**Comment by 0xffff11** [comment]
@mohammedrizwann123 #17 imo is also a low. You can read sherlocks docs that lead senior referenced. Thanks

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a valid low based on above comments

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [mohammedrizwann123](https://github.com/sherlock-audit/2023-04-ajna-judging/issues/18/#issuecomment-1621201146): rejected
