### ISSUE TITLE
Ruhum - `_roundToScale()` limits usage of low decimal tokens

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-ajna-judging#40]
Ruhum

medium

# `_roundToScale()` limits usage of low decimal tokens

## Summary
The `_roundToScale()` function rounds to 0 for low decimal tokens unless called with a large amount of tokens.

## Vulnerability Detail
`_roundToScale()` is defined in PoolHelper as:

```sol
    function _roundToScale(
        uint256 amount_,
        uint256 tokenScale_
    ) pure returns (uint256 scaledAmount_) {
        scaledAmount_ = (amount_ / tokenScale_) * tokenScale_;
    }
```

It's called multiple times throughout the codebase. One example is the `addCollateral()` function:
```sol
    function addCollateral(
        uint256 amountToAdd_,
        uint256 index_,
        uint256 expiry_
    ) external override nonReentrant returns (uint256 bucketLP_) {
        // ...

        amountToAdd_ = _roundToScale(amountToAdd_, _getArgUint256(COLLATERAL_SCALE));
        // ...
    }
```

`COLLATERAL_SCALE` is set in the factory contract by calling `_getTokenScale()` for the given ERC20 token:

```sol
    function _getTokenScale(address token_) internal view returns (uint256 scale_) {
        try IERC20Token(token_).decimals() returns (uint8 tokenDecimals_) {
            // revert if token decimals is more than 18
            if (tokenDecimals_ > 18) revert IPoolFactory.DecimalsNotCompliant();

            // scale calculated at pool precision (18)
            scale_ = 10 ** (18 - tokenDecimals_);
        } catch {
            // revert if token contract lack `decimals` method
            revert IPoolFactory.DecimalsNotCompliant();
        }
    }
```

If we use WBTC as our collateral, a token with 8 decimals, we get `10 ** (18 - 8) = 1e10` for `COLLATERAL_SCALE`. Using that as an input for `_roundToScale()`, we get `amount / 1e10 * 1e10`. Unless `amount >= 1e10`, `amount / 1e10` will be 0 causing the whole function to return 0. That means that you won't be able to deposit any collateral or do any of the other operations where `_roundToScale()` is called.

1e10 WBTC is about $2.5M. Pretty much nobody aside from whales will be able to use the WBTC market.

## Impact
Markets, where the collateral or quote token has low decimals, won't be usable unless you have a huge number of tokens.

## Code Snippet
https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/libraries/helpers/PoolHelper.sol#L260
https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/ERC20Pool.sol#L295
https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/ERC20PoolFactory.sol#L59
## Tool used

Manual Review

## Recommendation
use the user provided value for transfers and then scale it to 18 decimals for internal accounting if necessary.

**Comment by 0xruhum** [comment]
Escalate for 10 USDC

Since Ajna is supposed to work with [ERC20 tokens with less than 18 decimals](https://github.com/sherlock-audit/2023-04-ajna-0xruhum#q-which-erc20-tokens-do-you-expect-will-interact-with-the-smart-contracts) as well, this is a valid concern IMO.

**Comment by 0xffff11** [comment]
Seems like a medium to me. No loss of funds but a restriction towards specifics markets and who can interact with them.

**Comment by dmitriia** [comment]
It's not a bug at all, `_roundToScale()` creates values with collateral decimals from values with 18 decimals the protocol uses. Say WBTC just can't use decimals past 8th, so they are removed.

**Comment by 0xffff11** [comment]
Thanks for pointing out @dmitriia  After reviewing it with your extra context, I agree with this not being a bug. Invalid

**Comment by grandizzy** [comment]
pools accepts only WADs as input (e.g. when lender add quote token or when borrower draws debt they should specify amounts as WAD, regardless token precision)

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue based on the above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xruhum](https://github.com/sherlock-audit/2023-04-ajna-judging/issues/40/#issuecomment-1619882636): rejected
