### ISSUE TITLE
GimelSec - `PermitERC721.sol` should implement `supportsInterface`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-ajna-judging#61]
GimelSec

medium

# `PermitERC721.sol` should implement `supportsInterface`

## Summary

It is said that PermitERC721.sol should comply with EIP-4494.

https://github.com/sherlock-audit/2023-04-ajna-sces60107/tree/main#q-is-the-codecontract-expected-to-comply-with-any-eips-are-there-specific-assumptions-around-adhering-to-those-eips-that-watsons-should-be-aware-of
```text
Q: Is the code/contract expected to comply with any EIPs? Are there specific assumptions around adhering to those EIPs that Watsons should be aware of?
EIP-4494
```

And EIP-4494 indicate that:
https://eips.ethereum.org/EIPS/eip-4494
> This EIP requires EIP-165. EIP165 is already required in ERC-721, but is further necessary here in order to register the interface of this EIP. Doing so will allow easy verification if an NFT contract has implemented this EIP or not, enabling them to interact accordingly. The interface of this EIP (as defined in EIP-165) is 0x5604e225. Contracts implementing this EIP MUST have the supportsInterface function return true when called with 0x5604e225.

But `PermitERC721.sol` doesn’t implement `supportsInterface`

## Vulnerability Detail

It is said that PermitERC721.sol should comply with EIP-4494.
https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/base/PermitERC721.sol#L47
```solidity
/**
 *  @notice Functionality to enable `EIP-4494` permit calls as part of interactions with Position `NFT`s
 *  @dev    EIP-4494: https://eips.ethereum.org/EIPS/eip-4494
 *  @dev    References this implementation: https://github.com/dievardump/erc721-with-permits/blob/main/contracts/ERC721WithPermit.sol
 */
abstract contract PermitERC721 is ERC721, IPermit {
```

But PermitERC72.sol doesn’t implement `supportsInterface`. PositionManager inherits PermitERC72. PositionManager doesn’t implement `supportsInterface` either.
https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/PositionManager.sol#L40
```solidity
contract PositionManager is PermitERC721, IPositionManager, Multicall, ReentrancyGuard {
```

## Impact

Neither `PermitERC721.sol` nor `PositionManager.sol` implement `supportsInterface`. They should comply with EIP-4494

## Code Snippet

https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/base/PermitERC721.sol#L47
https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/PositionManager.sol#L40

## Tool used

Manual Review

## Recommendation

The reference implementation did implement `supportsInterface`. `PermitERC72.sol` can have a similar implementation.
https://github.com/dievardump/erc721-with-permits/blob/main/contracts/ERC721WithPermit.sol
```solidity
    function supportsInterface(bytes4 interfaceId)
        public
        view
        virtual
        override
        returns (bool)
    {
        return
            interfaceId == type(IERC721WithPermit).interfaceId || // 0x5604e225
            super.supportsInterface(interfaceId);
    }
```
Duplicate of #31

**Comment by sces60107** [comment]
Escalate for 10 USDC.

This issue should be a dup of https://github.com/sherlock-audit/2023-04-ajna-judging/issues/31. It mentions the issue that  PermitERC721.sol and PositionManager.sol doesn't comply with EIP-4494.

**Comment by 0xffff11** [comment]
I agree with escalation and a duplicate of #31

**Comment by 0xffff11** [comment]
See my comment in #31

**Comment by grandizzy** [comment]
https://github.com/ajna-finance/contracts/pull/907

**Comment by dmitriia** [comment]
> [ajna-finance/contracts#907](https://github.com/ajna-finance/contracts/pull/907)

Looks ok

**Comment by hrishibhat** [comment]
Result:
Low
Duplicate of #31

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [sces60107](https://github.com/sherlock-audit/2023-04-ajna-judging/issues/61/#issuecomment-1617137578): accepted
