### ISSUE TITLE
PRAISE - Malicious actor can steal collaterals from any bucket index because the  mergeOrRemoveCollateral() function misses the ownerOf check on the NFTs

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-ajna-judging#65]
PRAISE

high

# Malicious actor can steal collaterals from any bucket index because the  mergeOrRemoveCollateral() function misses the ownerOf check on the NFTs

## Summary
There should be ownerOf check on functions that transfer NFTs

## Vulnerability Detail
There should be checks to ensure that the caller/ msg.sender is the owner of the NFTs to withdraw as collateral from the provided list of bucket indices in the mergeOrRemoveCollateral() function.

Since the mergeOrRemoveCollateral() function allows claiming NFT collateral across multiple buckets there should be a ownerOf check to ensure that NFTs being withdrawn belongs to the caller.

## Impact
A Malicious actor can steal NFT collaterals from any bucket index.
## Code Snippet
https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/ERC721Pool.sol#L333
## Tool used

Manual Review

## Recommendation
you can add a check like this `require(ownerOf(tokenId) == msg.sender, Errors.ACCESS);`

**Comment by Love4codes** [comment]
Escalate for 10 USDC 

Since the mergeOrRemoveCollateral() function allows claiming NFT collateral across multiple buckets there should be a ownerOf check to ensure that NFTs being withdrawn belongs to the caller.

**Comment by dmitriia** [comment]
This looks invalid, as there is a check in LenderActions's _removeMaxCollateral() ensuring the caller can only reach own funds:

https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/libraries/external/LenderActions.sol#L658-L664

```solidity
        Lender storage lender = bucket.lenders[msg.sender];

        uint256 lenderLpBalance;

        if (bucket.bankruptcyTime < lender.depositTime) lenderLpBalance = lender.lps;
        // revert if no LP to redeem
        if (lenderLpBalance == 0) revert NoClaim();
```

**Comment by grandizzy** [comment]
The protocol has 2 functionalities wrt collateral: borrower can pledge collateral and draw debt or traders could add quote token or collateral in buckets and swap them. The functionality pointed out in issue is the swap one, so for example if someone add quote token at price 1000 and price goes down, a trader could add collateral at price 1000 and claim the quote tokens from bucket. same for collateral, one could add in bucket and take the quote tokens.
Hence no need to retain / enforce for the owner of collateral.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this issue a non-issue based on the above comments from Lead Watson and Sponsor

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Love4codes](https://github.com/sherlock-audit/2023-04-ajna-judging/issues/65/#issuecomment-1616781237): rejected
