### ISSUE TITLE
PRAISE - `collateralAmountToPull_`  will always be smaller than users inputted collateralAmountToPull_ due to precision loss in _roundToScale() function

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-ajna-judging#9]
PRAISE

medium

# `collateralAmountToPull_`  will always be smaller than users inputted collateralAmountToPull_ due to precision loss in _roundToScale() function

## Summary
dividing before multiplying causes precision loss in solidity

## Vulnerability Detail
in the repayDebt() function users inputted `collateralAmountToPull_` is updated with _roundToScale() result 

_roundToScale() does some calculation with users inputted `collateralAmountToPull_` and COLLATERAL_SCALE which is 93 but the issue is that it divides before multiplying causing precision loss 
```solidity
function _roundToScale(
        uint256 amount_,//audit-info this is `collateralAmountToPull_` 
        uint256 tokenScale_//@audit-info this is COLLATERAL_SCALE which is 93
    ) pure returns (uint256 scaledAmount_) {
        scaledAmount_ = (amount_ / tokenScale_) * tokenScale_;
    }

```
So lets say user inputs 1000.000000(the extra decimal places represent the token decimal, this one is 6 for USDC) as `collateralAmountToPull_`, when this line `collateralAmountToPull_  = _roundToScale(collateralAmountToPull_,     _getArgUint256(COLLATERAL_SCALE));` is executed, it will reduce the 1000.000000 inputted to 930 because of precision loss.

Solidity truncates values during division.
## Impact
`repayDebt()` function will always update `collateralAmountToPull_` to something less than what user inputted every time. 
User will always reduce less amount of collateral than what he inputted when executing the repayDebt() function.
## Code Snippet
https://github.com/sherlock-audit/2023-04-ajna/blob/main/ajna-core/src/ERC20Pool.sol#L220

## Tool used

Manual Review

## Recommendation
don't divide before multiplying in the _roundToScale() function.
And also look for another way to scale tokens with decimals <18

**Comment by Love4codes** [comment]
Escalate for 10 USDC

I know this was done to scale tokens with less than 18 decimals but the value will be reduced more than should be. 

Like for example, So lets say user inputs 1000.000000(the extra decimal places represent the token decimal, this one is 6 for USDC) as collateralAmountToPull_, when this line collateralAmountToPull_  = _roundToScale(collateralAmountToPull_,     _getArgUint256(COLLATERAL_SCALE)); is executed, it will reduce the 1000.000000 inputted to 930 because of precision loss.

Solidity truncates values during division.

**Comment by 0xffff11** [comment]
After escalation and the numerical example, I can see the issue as a medium. Watson shows how the calculation impacts in the return value.

**Comment by dmitriia** [comment]
Similarly to #76 it is a conversion from protocol wide 18dp to collateral precision. For example, it is impossible to pull a WBTC amount with more than 8 dp precision, so it has to be rounded

**Comment by Love4codes** [comment]
> Similarly to #76 it is a conversion from protocol wide 18dp to collateral precision. For example, it is impossible to pull a WBTC amount with more than 8 dp precision, so it has to be rounded

Yes boss, but the rounding will always reduce the inputted value more than should be

**Comment by dmitriia** [comment]
This is user input correction that has to be done either way. It can be treated as a user mistake if extra decimals were entered in the first place.

**Comment by Love4codes** [comment]
> This is user input correction that has to be done either way. It can be treated as a user mistake if extra decimals were entered in the first place.

boss this issue isn't about user mistake due to user wrong input...

The issue here is division before multiplication which is popularly known to cause rounding error due to the fact that solidity truncates values during division. 

so whether the user enters extra decimals or not whatever he gives as input will be adversely reduced due to the division before multiplication

**Comment by grandizzy** [comment]
Similar with comment https://github.com/sherlock-audit/2023-04-ajna-judging/issues/5#issuecomment-1630119876 this would be valid if `COLLATERAL_SCALE=93` but this cannot happen.  The collateral scale is calculated in `_getTokenScale` function https://github.com/ajna-finance/ajna-core/blob/main/src/base/PoolDeployer.sol#L59 as
```
scale_ = 10 ** (18 - tokenDecimals_);
```
so it can only be a pow of 10, e.g. 1, `10**1, 10**2 ... 10**18`

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low based on the above comments.

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Love4codes](https://github.com/sherlock-audit/2023-04-ajna-judging/issues/9/#issuecomment-1616788933): rejected
